- _data/sponsors.yml
- _includes/sponsors.html
* moved 2020 sponsors not confirmed for 2021 to a holding spot where they hopefully won't show up anywhere but we still have the data handy to reuse if needed
* partially completes #23 , but we should leave it open for now
> updated sponsors with those who have confirmed

- _config.yml
> updated code of conduct contact

- _data/sessions.yml
For each lightning talk session, added intro. and title of each talk. Updated keywords and audience for both sessions (based on proposals file).
> Lightning Talks Data Update

- _includes/speaker-div.html
Hopefully addresses #100 --
The images used as links in this issue didn't have any alt text -- hopefully adding some alt text will resolve the problem?
> add alt text to social icons

- _config.yml
- _includes/serviceproject.html
* closes #101
* closes #102
* adds alt text to image and only renders service project title if there's content for it
> accessibility fixes for service project section

- _config.yml
- awards.html
* remove last of the live 2020 data in config.yml (some things are still commented out and that's ok for now.) 
* show awards time as TBA until we get a time set
* partially addresses #39
> 2021 config updates

- _config.yml
comments out some currently unused other google keys; siteVerification will be added soon
> update google analytics ID for 2021

- _config.yml
> update ticket availability

- _data/sessions.yml
Updated event description and added 2nd speaker
> Update AMA event information

- _config.yml
- _data/sessions.yml
* added time to /awards page
* added awards time to /schedule
> Add awards time info

- _data/schedule.yml
on schedule page, show "Friday, October 29" instead of just "October 29", etc
> add day of week to schedule

- _data/sponsors.yml
at the request of Allen Reichert (vendor liaison), adds the two individual session sponsors to the front page under "additional support"
* OLSSI & RPC (Research & Publications) logos
> adds "additional sponsors" to front page

- _data/sessions.yml
* closes #158 
* closes #159 
* closes #161
> add details for IG lunches

- _data/schedule.yml
* closes #162 
* changes time of business meeting from 3pm to 2:30 to allow time before the preconference
> change time of business meeting to 2:30

- _config.yml
* closes #165 
* takes the existing sponsors page and adds it as a link in the main menu
> add "sponsors" link to main menu

- _config.yml
> remove scholarship button

- _data/sessions.yml
Adds registration link to session description
> Add AMA event registration link

- _data/sessions.yml
> added some missing session descriptions

- _data/awards_2021.json
> remove daniela solomon from award page

- _config.yml
- _data/sessions.yml
- _includes/about-preconference2.html
- _includes/sessions-modals.html
* adds settings to hide feedback and live session links after the conference 
* activates those settings
* hides Ask Me Anything link from the session preview
> Post conference settings: hide Zoom, registration, feedback links
